-- ── Weekly Chronicle Updates ─────────────────────────────────────────────────
-- Stores auto-generated weekly summaries of hobby and crusade progress
-- per campaign. Generated by the /api/cron/weekly-updates cron (Fridays 08:00).
-- Each row covers one update_type for one campaign for one week.

CREATE TABLE IF NOT EXISTS chronicle_weekly_updates (
  id          UUID        PRIMARY KEY DEFAULT gen_random_uuid(),
  campaign_id UUID        NOT NULL REFERENCES campaigns(id) ON DELETE CASCADE,
  update_type TEXT        NOT NULL CHECK (update_type IN ('hobby_progress', 'army_progress')),
  week_start  TIMESTAMPTZ NOT NULL,
  week_end    TIMESTAMPTZ NOT NULL,
  -- content: JSON array of player summaries
  -- [ { player_id, username, lines: string[] }, ... ]
  content     JSONB       NOT NULL DEFAULT '[]'::jsonb,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT NOW(),

  -- One row per campaign + type + week
  UNIQUE (campaign_id, update_type, week_start)
);

-- Index for chronicle page query (campaign_id + newest first)
CREATE INDEX IF NOT EXISTS idx_weekly_updates_campaign
  ON chronicle_weekly_updates (campaign_id, created_at DESC);

-- ── RLS ───────────────────────────────────────────────────────────────────────
ALTER TABLE chronicle_weekly_updates ENABLE ROW LEVEL SECURITY;

-- Campaign members and the campaign organiser can read
CREATE POLICY "members_can_read_weekly_updates"
  ON chronicle_weekly_updates
  FOR SELECT
  USING (
    EXISTS (
      SELECT 1 FROM campaign_members cm
      WHERE cm.campaign_id = chronicle_weekly_updates.campaign_id
        AND cm.user_id = auth.uid()
    )
    OR EXISTS (
      SELECT 1 FROM campaigns c
      WHERE c.id = chronicle_weekly_updates.campaign_id
        AND c.organiser_id = auth.uid()
    )
  );

-- Service role (cron) writes — no explicit policy needed (bypasses RLS).
-- If using anon/authenticated role for cron, add an INSERT policy here.
